development:
  sessions:
    default:
      database: offers_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: offers_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
